version: "3.8"

networks:
  beerfinder_network:

volumes:
  PostgreData:

services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    ports:
      - "8080:80"
    networks:
      - beerfinder_network
    depends_on:
      - postgresql

  postgresql:
    image: ankane/pgvector:latest
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: beerfinder
      POSTGRES_USER: sail
      POSTGRES_PASSWORD: password
    volumes:
      - PostgreData:/var/lib/postgresql/data
    networks:
      - beerfinder_network
